# fly.toml app configuration file generated for appointment-system-nodejs on 2024-11-16T17:44:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'appointment-system-nodejs'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  SALT_WORK_FACTOR = '10'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
