name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '*'

jobs:
  test:
    name: 🔑 Test
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy with flyctl
        run: |
          flyctl deploy --remote-only \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
